### 1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

### 2. Print the NUMPY version and the configuration.

In [3]:
np.__version__


'1.26.3'

In [4]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2628220032720
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.3
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.7
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
### Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [10]:
a = np.random.randint(10, size=(2,3,5))

In [11]:
a_1 = np.random.random((2,3,5))

In [12]:
a_2 = np.random.randn(2, 3, 5)

### 4. Print a.

In [14]:
print(a)

[[[5 0 6 4 6]
  [9 4 7 0 4]
  [3 1 5 6 1]]

 [[2 1 2 3 9]
  [8 0 6 2 9]
  [2 9 5 6 7]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"

In [19]:
b = np.ones((5,2,3))

### 6. Print b.

In [20]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


### 7. Do a and b have the same size? How do you prove that in Python code?

In [21]:
print(a.size)
print(b.size)
comp = a.size == b.size
print(comp)

30
30
True


### 8. Are you able to add a and b? Why or why not?

In [22]:
array_sum = a + b
print(array_sum)

#No se pueden sumar simplemente. Pues su "shape" no es compatible (2,3,5) y (5,2,3)
#El error indica ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [23]:
c = np.transpose(b, (1,2,0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


### 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [25]:
d = a + c
print(d)
#Los dos tienen la misma "shape" (2,3,5)

[[[ 6.  1.  7.  5.  7.]
  [10.  5.  8.  1.  5.]
  [ 4.  2.  6.  7.  2.]]

 [[ 3.  2.  3.  4. 10.]
  [ 9.  1.  7.  3. 10.]
  [ 3. 10.  6.  7.  8.]]]


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [26]:
print(a)
print(d)
#El array "c" salió de usar .ones() y convertirse todo en "1" y después de usar transpose() todos sus 
#valores incrementaron en "1"
#Y luego los dos arrays tenian la misma "shape"

[[[5 0 6 4 6]
  [9 4 7 0 4]
  [3 1 5 6 1]]

 [[2 1 2 3 9]
  [8 0 6 2 9]
  [2 9 5 6 7]]]
[[[ 6.  1.  7.  5.  7.]
  [10.  5.  8.  1.  5.]
  [ 4.  2.  6.  7.  2.]]

 [[ 3.  2.  3.  4. 10.]
  [ 9.  1.  7.  3. 10.]
  [ 3. 10.  6.  7.  8.]]]


### 12. Multiply a and c. Assign the result to e.

In [27]:
e = a*c
print(e)

[[[5. 0. 6. 4. 6.]
  [9. 4. 7. 0. 4.]
  [3. 1. 5. 6. 1.]]

 [[2. 1. 2. 3. 9.]
  [8. 0. 6. 2. 9.]
  [2. 9. 5. 6. 7.]]]


### 13. Does e equal to a? Why or why not?

In [28]:
print(e == a)
#como el array "c" son todo "1" al multiplicar los valores del array "a" por uno resultará en dos arrays de mismos valores.

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [30]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

10.0
1.0
5.4


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [32]:
f = np.empty_like(d)


16. Populate the values in f. 
For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.


In [35]:
populate_f = {d_min: 0, d_mean: 50, d_max: 100}
f = np.zeros_like(d)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75
            else:
                f[i, j, k] = populate_f[value]

print(f)


[[[ 75.   0.  75.  25.  75.]
  [100.  25.  75.   0.  25.]
  [ 25.  25.  75.  75.  25.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.   0.  75.  25. 100.]
  [ 25. 100.  75.  75.  75.]]]


In [ ]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [36]:
print(d)
print(f)
#no me sale igual  :(

[[[ 6.  1.  7.  5.  7.]
  [10.  5.  8.  1.  5.]
  [ 4.  2.  6.  7.  2.]]

 [[ 3.  2.  3.  4. 10.]
  [ 9.  1.  7.  3. 10.]
  [ 3. 10.  6.  7.  8.]]]
[[[ 75.   0.  75.  25.  75.]
  [100.  25.  75.   0.  25.]
  [ 25.  25.  75.  75.  25.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.   0.  75.  25. 100.]
  [ 25. 100.  75.  75.  75.]]]


In [ ]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

In [38]:
populate_f = {d_min: "A", d_mean: "B", d_max: "C"}
f = np.zeros_like(d, dtype=str)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if d_min < value < d_mean:
                f[i, j, k] = "D"
            elif d_mean < value < d_max:
                f[i, j, k] = "E"
            else:
                f[i, j, k] = populate_f[value]
print(f)

[[['E' 'A' 'E' 'D' 'E']
  ['C' 'D' 'E' 'A' 'D']
  ['D' 'D' 'E' 'E' 'D']]

 [['D' 'D' 'D' 'D' 'C']
  ['E' 'A' 'E' 'D' 'C']
  ['D' 'C' 'E' 'E' 'E']]]
